name: spendly
description: "Track your expenses effortlessly with SpendX - Android Only"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^3.0.0
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  glassmorphism: ^3.0.0
  path_provider: ^2.1.0
  permission_handler: ^12.0.0
  file_picker: ^8.0.0
  uuid: ^4.5.2
  pdf: ^3.11.3
  printing: ^5.11.0
  csv: ^6.0.0
  share_plus: ^12.0.1
  open_file: ^3.5.10
  crypto: ^3.0.3
  encrypt: ^5.0.3
  table_calendar: ^3.0.9
  url_launcher: ^6.3.1
  http: ^1.6.0
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/bank/
    - assets/img/cash/
    - assets/img/avatar/
    - assets/img/bg/
    - assets/img/logo/logo2.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/img/logo/logo1.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/logo/logo1.jpg"
